twitter/authApp/urls.py
from django.urls import path, re_path

from .views import loginView, logout_view, profileView, registerView

urlpatterns = [
    path("login/", loginView, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", registerView, name="register"),
    path("profile/", profileView, name="profile"),
]

twitter/twitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tweetApp.urls")),
    path("", include("authApp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/authApp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    first_name = models.CharField(blank=False, null=False, max_length=100)
    last_name = models.CharField(blank=False, null=False, max_length=100)
    avatar = models.ImageField(upload_to="avatar/", default="avatar/default.png")
    background = models.ImageField(
        upload_to="background/", default="background/default_background.png"
    )
    description = models.TextField(blank=False, null=False)
    city = models.CharField(blank=False, null=False, max_length=100)
    country = models.CharField(blank=False, null=False, max_length=100)
    user = models.OneToOneField(to=get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.user.username}'s Profile')"

twitter/authApp/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    city = forms.CharField(required=False)
    country = forms.CharField(required=False)
    description = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = Profile
        exclude = ["user"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "max-width: 350px, margin-top: 20px",
                "autofocus": '""',
            }
        )
        self.fields["last_name"].widget.attrs.update({"class": "form-control"})
        self.fields["city"].widget.attrs.update({"class": "form-control"})
        self.fields["country"].widget.attrs.update({"class": "form-control"})
        self.fields["description"].widget.attrs.update(
            {
                "class": "form-control",
                "rows": "5",
                "placeholder": "Tell us a little bit about yourself...",
                "style": "min-height:100px",
            }
        )

twitter/authApp/views.py
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST
from django.views.generic.edit import UpdateView

from .forms import ProfileForm


@require_POST
def loginView(request):
    if request.is_ajax():
        data = json.loads(request.body)
        user = authenticate(**data)
        if user is not None:
            login(request, user)
            return JsonResponse({"error": "None"}, status=200)
        else:
            return JsonResponse(
                {"error": "The combination of Username/Password is not correct."},
                status=400,
            )


@require_POST
def logout_view(request):
    logout(request)
    return redirect("home")


@require_POST
def registerView(request):
    if request.is_ajax():
        data = json.loads(request.body)
        form = UserCreationForm(data)
        if form.is_valid():
            form.save()
            return JsonResponse({"error": "None"}, status=200)
        else:
            return JsonResponse({"error": form.errors}, status=400)


@login_required
def profileView(request):
    if request.method == "POST":
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if profile_form.is_valid():
            profile_form.save()
            return redirect("account-detail", username=request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, "authApp/profile.html", {"form": profile_form})

twitter/authApp/templates/authApp/profile.html
{% extends "tweetApp/base.html" %}

{% block main %}
<div class="container-fluid" style="margin-top: max(10vh, 65px); text-align: center;">
    <div class="row">
        <div class="col-sm" style="display: inline-block;">
            <form method="POST" action="/profile/" style="display: inline-block;" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-auto">
                    <div class="form-floating mb-3">
                        Your Profile Picture:
                        <img src="{{request.user.profile.avatar.url}}" class="img-thumbnail" style="height: auto; max-height: 200px; width: auto; max-width: 200px; margin-bottom: 10px;">
                        <input type="file" name="avatar" accept="image/*" id="id_avatar">
                    </div>
                    <div class="form-floating mb-3">
                        Your Background Picture:
                        <img src="{{request.user.profile.background.url}}" class="img-thumbnail" style="height: auto; max-height: 200px; width: auto; max-width: 400px; margin-bottom: 10px;">
                        <input type="file" name="background" accept="image/*" id="id_avatar">
                    </div>
                </div>
                <div class="col-auto" style="width: min(400px,80%); display: inline-block;">
                    {{ form.non_field_errors }}
                    <div class="form-floating mb-3">
                        {{ form.first_name.errors }}
                        {{ form.first_name }}
                        <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.last_name.errors }}
                        {{ form.last_name }}
                        <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.city.errors }}
                        {{ form.city }}
                        <label for="{{ form.city.id_for_label }}">City:</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.country.errors }}
                        {{ form.country }}
                        <label for="{{ form.country.id_for_label }}">Country:</label>
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.description.errors }}
                        {{ form.description }}
                        <label for="{{ form.description.id_for_label }}">Description:</label>
                    </div>
                    
                <button type="submit" class="btn btn-secondary">Submit</button>
                </div>
            </form>
    </div>
</div>
{% endblock %}